{
 "title": "VPN Tunnel Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_uptime,environment)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_uptime{environment=\"$d_environment\"},host_name)"
    }
   },
   {
    "name": "d_namespace",
    "label": "Context:",
    "query": {
     "query": "label_values(system_uptime{host_name=\"$d_hostname\", environment=\"$d_environment\"}, service_namespace)"
    }
   },
   {
    "name": "d_probename",
    "label": "Probe name:",
    "query": {
     "query": "label_values(network_probes_state{host_name=\"$d_hostname\", environment=\"$d_environment\", service_namespace=\"$d_namespace\"}, name)"
    }
   },
   {
    "name": "d_probeid",
    "label": "Probe ID:",
    "query": {
     "query": "label_values(network_probes_state{host_name=\"$d_hostname\", environment=\"$d_environment\", service_namespace=\"$d_namespace\", name=\"$d_probename\"}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Probe Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probe Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Probe Protocol",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(network_probes_mode{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(network_probes_state{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "Probe State"
    }
   ]
  },
  {
   "title": "Probe State History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "clamp (last_over_time(network_probes_state{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s]), 0, 1)",
     "legendFormat": "Probe State"
    }
   ]
  },
  {
   "title": "Probe Source",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(network_probes_state{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Probe Destination",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(network_probes_state{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  { "title": "VPN Tunnel Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Tunnel Peer Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "Peer Main IP Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{peer_main_ip}}"
    }
   ]
  },
  {
   "title": "Tunnel State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "Tunnel State"
    }
   ]
  },
  {
   "title": "Tunnel State History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "clamp (last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s]), 0, 1)",
     "legendFormat": "Tunnel State"
    }
   ]
  },
  {
   "title": "Tunnel Encryption Settings",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{tunnel_methods}}"
    }
   ]
  },
  {
   "title": "Tunnel Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{tunnel_type}}"
    }
   ]
  },
  {
   "title": "Tunnel Traffic Report",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel_encrypted_bytes{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "Encrypted"
    },
    {
     "expr": "last_over_time(vpn_probes_tunnel_decrypted_bytes{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "Decrypted"
    }
   ]
  },
  {
   "title": "Tunnel Traffic Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (id) (vpn_probes_tunnel_encrypt_throughput{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"})",
     "legendFormat": "Encrypt rate"
    },
    {
     "expr": "sum by (id) (vpn_probes_tunnel_decrypt_throughput{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"})",
     "legendFormat": "Decrypt rate"
    }
   ]
  },
  {
   "title": "Tunnel Local IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{local_ip}}"
    }
   ]
  },
  {
   "title": "Tunnel Remote IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{remote_ip}}"
    }
   ]
  },
  {
   "title": "Local Tunnel Traffic Selectors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{local_ts}}"
    }
   ]
  },
  {
   "title": "Remote Tunnel Traffic Selectors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s])",
     "legendFormat": "{{remote_ts}}"
    }
   ]
  },
  {
   "title": "Tunnel Creation Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel_generated_time{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s]) * 1000",
     "legendFormat": "Tunnel created"
    }
   ]
  },
  {
   "title": "Tunnel Expiration Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vpn_probes_tunnel_expire_time{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", id=~\"$d_probeid\"}[30s]) * 1000",
     "legendFormat": "Tunnel created"
    }
   ]
  }
 ]
}